version: '3'
services:
  stalwart-mail:
    image: stalwartlabs/mail-server:latest
    ports:
      - 443:443 
      - 25:25 
      - 587:587 
      - 465:465    
      - 143:143 
      - 993:993 
      - 4190:4190 
    volumes:
      - ./volumes/stalwart-mail:/opt/stalwart-mail 
    networks:
       mail-net:
         ipv4_address: 10.30.40.2
  lldap:
    image: lldap/lldap:stable
    ports:
      # For LDAP, not recommended to expose, see Usage section.
      #- "3890:3890"
      # For LDAPS (LDAP Over SSL), enable port if LLDAP_LDAPS_OPTIONS__ENABLED set true, look env below
      - 6360:6360
      # For the web front-end
      - 17170:17170"
    volumes:
      - ./volumes/lldap_data:/data"
      # Alternatively, you can mount a local folder
      # - "./lldap_data:/data"
    environment:
      - UID=100001
      - GID=100001
      - TZ=Asia/Colombo
      - LLDAP_JWT_SECRET=${REPLACE_WITH_RANDOM}
      - LLDAP_KEY_SEED=${REPLACE_WITH_RANDOM}
      - LLDAP_LDAP_BASE_DN=dc=example,dc=com
      # If using LDAPS, set enabled true and configure cert and key path
      - LLDAP_LDAPS_OPTIONS__ENABLED=true
      - LLDAP_LDAPS_OPTIONS__CERT_FILE=/path/to/certfile.crt
      - LLDAP_LDAPS_OPTIONS__KEY_FILE=/path/to/keyfile.key
      # You can also set a different database:
      # - LLDAP_DATABASE_URL=mysql://mysql-user:passwrd@mysql-server/my-database
      - LLDAP_DATABASE_URL=postgres://${POSTGRES_USER}:POSTGRESS_PASSWORD}@postgres-db/lldap
  networks:
    mail-net:
      ipv4_address: 10.30.40.3

networks:
  mail-net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.30.40.0/24
