version: '3'
services:
  stalwart-mail:
    image: stalwartlabs/mail-server:latest
    ports:
      - 443:443 
      - 25:25 
      - 587:587 
      - 465:465    
      - 143:143 
      - 993:993 
      - 4190:4190 
    volumes:
      - ./volumes/stalwart-mail:/opt/stalwart-mail 
    networks:
       mail-net:
         ipv4_address: 10.30.40.2

networks:
  acmenet:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.30.40.0/24
